#######
#SEND EMAIL
#######
POST http://localhost:5300/api/email
Content-Type: application/json

{
 "name": "Your User",
 "subject": "I like your website",
    "message": "Please let me know about your website",
    "email": "test@test.com"
}